services:
  - type: web
    name: event-monolith-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # User needs to set this in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://${RENDER_EXTERNAL_HOSTNAME}
    healthCheckPath: /
    autoDeploy: true